name = "OctofitterInterferometry"
uuid = "1a3c1578-c182-4e42-bc1e-b4981e19ba9a"
authors = ["Dori Blakely", "William Thompson <will.thompson@outlook.com>"]
version = "0.7.1"

[deps]
Octofitter = "daf3887e-d01a-44a1-9d7e-98f15c5d69c9"
PlanetOrbits = "fd6f9641-d78f-43ce-a379-ceb0bddb468a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
