[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PlanetOrbits = "fd6f9641-d78f-43ce-a379-ceb0bddb468a"

using Octofitter, Distributions
using Random
using StatsBase
using MCMCChains
using Plots
using CairoMakie: Makie
using PairPlots

[compat]
Documenter = "0.27"
